"""Generate LinkML schema modules from Open Policy Agent source artifacts.

Reads upstream OPA source files and emits one LinkML schema submodule per
source under ``src/opa/schema/`` plus a corresponding instance YAML fixture
under ``tests/data/valid/``.

Sources:

* ``builtin_metadata.json``              -> ``builtin_metadata.yaml``
* ``capabilities.json``                  -> ``capabilities.yaml``
* ``v1/ast/version_index.json``          -> ``version_index.yaml``
* ``v1/schemas/authorizationPolicy.json`` -> ``authorization_input.yaml``
* ``v1/bundle/manifest.schema.json``     -> ``bundle_manifest.yaml``
* ``v1/ir/plan.schema.json``             -> ``ir_plan.yaml``

Run from the ``linkml/`` directory::

    uv run python scripts/gen_linkml.py all

or one module at a time::

    uv run python scripts/gen_linkml.py capabilities
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from collections import OrderedDict
from pathlib import Path
from typing import Any

import yaml


HERE = Path(__file__).resolve().parent
LINKML_ROOT = HERE.parent
OPA_ROOT = LINKML_ROOT.parent
SCHEMA_DIR = LINKML_ROOT / "src" / "opa" / "schema"
TESTS_VALID = LINKML_ROOT / "tests" / "data" / "valid"

CAPABILITIES_JSON = OPA_ROOT / "capabilities.json"
BUILTIN_METADATA_JSON = OPA_ROOT / "builtin_metadata.json"
VERSION_INDEX_JSON = OPA_ROOT / "v1" / "ast" / "version_index.json"
AUTH_INPUT_JSON = OPA_ROOT / "v1" / "schemas" / "authorizationPolicy.json"
BUNDLE_MANIFEST_JSON = OPA_ROOT / "v1" / "bundle" / "manifest.schema.json"
IR_PLAN_JSON = OPA_ROOT / "v1" / "ir" / "plan.schema.json"

# Upstream OPA repo (used to construct fully-qualified ``source:`` URLs so the
# generated schemas point at the exact file the data was derived from).
_OPA_SOURCE_BASE = "https://github.com/open-policy-agent/opa/blob/main/"

# Schema version for every emitted submodule. Bump when the generator changes
# the shape of any submodule in a non-backwards-compatible way.
SCHEMA_VERSION = "0.1.0"


def _source_url(rel_path: str) -> str:
    """Return the upstream URL for an OPA source artifact (used for ``source:``)."""
    return _OPA_SOURCE_BASE + rel_path


HEADER = (
    "# AUTOGENERATED by linkml/scripts/gen_linkml.py from upstream OPA sources.\n"
    "# Do not edit by hand; rerun `just gen-linkml`.\n"
)


# --------------------------------------------------------------------------- #
# YAML dumping helpers (deterministic, key-ordered, literal block strings)    #
# --------------------------------------------------------------------------- #


class _Dumper(yaml.SafeDumper):
    def increase_indent(self, flow=False, indentless=False):  # type: ignore[override]
        return super().increase_indent(flow, False)


def _represent_mapping(dumper: yaml.Dumper, data: dict) -> Any:
    return dumper.represent_mapping("tag:yaml.org,2002:map", data.items())


def _represent_str(dumper: yaml.Dumper, data: str) -> Any:
    if "\n" in data:
        return dumper.represent_scalar("tag:yaml.org,2002:str", data, style="|")
    return dumper.represent_scalar("tag:yaml.org,2002:str", data)


_Dumper.add_representer(dict, _represent_mapping)
_Dumper.add_representer(OrderedDict, _represent_mapping)
_Dumper.add_representer(str, _represent_str)


def dump_yaml(path: Path, data: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    # width=78 keeps generator output within the yamllint warn threshold of 88
    # columns (the config allows long unbreakable URLs / CURIEs to spill).
    text = yaml.dump(
        data,
        Dumper=_Dumper,
        sort_keys=False,
        default_flow_style=False,
        width=78,
        allow_unicode=True,
    )
    path.write_text(HEADER + _blank_line_entities(_blank_line_sections(text)))
    rel = path.relative_to(LINKML_ROOT)
    print(f"wrote {rel}", file=sys.stderr)


# Top-level schema sections that should be visually separated by blank lines
# in the rendered YAML (SKILL guidance: "Separate major/minor elements with
# blank lines for readability (i.e. prefixes, imports, classes, slots, enums,
# subsets and sub-elements)").
_TOP_LEVEL_SECTIONS = (
    "prefixes:",
    "imports:",
    "source:",
    "see_also:",
    "annotations:",
    "types:",
    "subsets:",
    "slots:",
    "classes:",
    "enums:",
)


def _blank_line_sections(text: str) -> str:
    """Insert a blank line before each top-level schema section header."""
    out_lines: list[str] = []
    for line in text.splitlines():
        if (
            out_lines
            and out_lines[-1] != ""
            and any(line.startswith(s) for s in _TOP_LEVEL_SECTIONS)
        ):
            out_lines.append("")
        out_lines.append(line)
    return "\n".join(out_lines) + "\n"


def _blank_line_entities(text: str) -> str:
    """Insert blank lines between notable entities for readability.

    Adds spacing between sibling entries in top-level mapping-heavy sections:
    ``subsets``, ``types``, ``slots``, ``classes``, and ``enums``.
    """
    spaced: list[str] = []
    current_section: str | None = None
    entity_sections = {"subsets", "types", "slots", "classes", "enums"}
    top_entity_key = re.compile(r"^  [^\s].*:$")

    for line in text.splitlines():
        if re.match(r"^[a-z_]+:$", line):
            current_section = line[:-1]

        if (
            current_section in entity_sections
            and top_entity_key.match(line)
            and spaced
            and spaced[-1] != ""
            and top_entity_key.match(spaced[-1])
        ):
            spaced.append("")

        spaced.append(line)

    return "\n".join(spaced) + "\n"


# --------------------------------------------------------------------------- #
# Common schema-header builder                                                #
# --------------------------------------------------------------------------- #


def schema_header(local: str, description: str) -> dict:
    """Return a LinkML schema header for module ``opa.<local>``.

    Prefix choice notes (per SKILL ``Prefixes Reference``):

    * ``openpolicyagent`` is used instead of the natural ``opa`` because the
      latter is already canonicalised by bioregistry to an unrelated namespace
      (``adream``), which would trip ``linkml-lint``'s ``canonical_prefixes``
      rule. The IRI still matches the schema ``id``.
    * ``rdfs``, ``dcterms`` and ``schema`` are declared up-front because the
      common slot-URI post-processor (``_align_common_slot_uris``) maps
      ``name`` / ``description`` / ``title`` slots to those vocabularies.
    """
    core_subset = f"{local}_core_elements"
    supporting_subset = f"{local}_supporting_elements"

    return {
        "id": f"https://w3id.org/lmodel/opa/{local}",
        "name": local,
        "title": local.replace("_", " ").title(),
        "description": description,
        "license": "Apache-2.0",
        "version": SCHEMA_VERSION,
        "prefixes": {
            "openpolicyagent": "https://w3id.org/lmodel/opa/",
            "linkml": "https://w3id.org/linkml/",
            "schema": "http://schema.org/",
            "dcterms": "http://purl.org/dc/terms/",
            "rdfs": "http://www.w3.org/2000/01/rdf-schema#",
        },
        "default_prefix": "openpolicyagent",
        "default_range": "string",
        "imports": ["linkml:types"],
        "subsets": {
            core_subset: {
                "description": "Primary document/root entities for this module.",
            },
            supporting_subset: {
                "description": "Supporting structural or helper entities.",
            },
        },
    }


# --------------------------------------------------------------------------- #
# Cross-cutting schema post-processors (FAIR alignment, hygiene)              #
# --------------------------------------------------------------------------- #


def _align_common_slot_uris(schema: dict) -> None:
    """Map common attribute names to canonical FAIR vocabulary URIs.

    SKILL guidance: when a slot is semantically equal to a term in DC,
    schema.org, FOAF, RDFS, etc., wire its ``slot_uri`` (or ``exact_mappings``
    for identifier slots) to that resolvable term instead of leaving it as the
    schema-local default.
    """
    for cls in schema.get("classes", {}).values():
        for slot_name, slot_def in (cls.get("attributes") or {}).items():
            if not isinstance(slot_def, dict):
                continue
            if slot_name == "name":
                if slot_def.get("identifier"):
                    slot_def.setdefault(
                        "exact_mappings",
                        ["schema:identifier", "dcterms:identifier"],
                    )
                else:
                    slot_def.setdefault("slot_uri", "rdfs:label")
            elif slot_name == "description":
                slot_def.setdefault("slot_uri", "schema:description")
            elif slot_name == "title":
                slot_def.setdefault("slot_uri", "dcterms:title")


def _dedupe_enum_descriptions(schema: dict) -> None:
    """Drop ``description: <symbol>`` entries that add no information.

    Many source-driven enums (e.g. ``BuiltinTypeKind``) carry permissible
    values whose only documentation is the symbol itself. Removing the
    redundant ``description`` keeps the rendered YAML focused on entries that
    actually carry extra context (slugged symbols, ``meaning`` mappings, etc.).
    """
    for enum_def in (schema.get("enums") or {}).values():
        for symbol, pv in (enum_def.get("permissible_values") or {}).items():
            if not isinstance(pv, dict):
                continue
            if pv.get("description") == symbol:
                pv.pop("description", None)


def _finalize_schema(schema: dict) -> dict:
    """Apply all cross-cutting post-processors in a fixed order."""
    _align_common_slot_uris(schema)
    _dedupe_enum_descriptions(schema)
    _add_default_subset_membership(schema)
    return schema


def _add_default_subset_membership(schema: dict) -> None:
    """Assign each class to a default subset for navigation and grouping."""
    subsets = schema.get("subsets") or {}
    if not isinstance(subsets, dict):
        return
    core_subset = next((k for k in subsets if k.endswith("_core_elements")), None)
    supporting_subset = next(
        (k for k in subsets if k.endswith("_supporting_elements")), None
    )
    if not core_subset or not supporting_subset:
        return

    classes = schema.get("classes") or {}
    if not isinstance(classes, dict):
        return
    for class_def in classes.values():
        if not isinstance(class_def, dict):
            continue
        in_subset = class_def.get("in_subset")
        if in_subset:
            continue
        if class_def.get("tree_root"):
            class_def["in_subset"] = [core_subset]
        else:
            class_def["in_subset"] = [supporting_subset]


# --------------------------------------------------------------------------- #
# Module: capabilities                                                        #
# --------------------------------------------------------------------------- #


# Structural type-kinds observed in capabilities.json:
#   string, number, boolean, null, any, array, set, object, function
CAPABILITIES_TYPE_KINDS = [
    "string",
    "number",
    "boolean",
    "null",
    "any",
    "array",
    "set",
    "object",
    "function",
]


def build_capabilities_schema(data: dict) -> dict:
    """Build the LinkML schema describing capabilities.json shape.

    Enum permissible-values for ``FeatureName`` and ``FutureKeyword`` are
    seeded from the live data so the schema reflects what the upstream OPA
    release currently advertises. Unknown values are still accepted because
    the slot ``range`` falls back to ``string`` when no enum match is found.
    """
    feature_values = sorted(set(data.get("features") or []))
    future_keyword_values = sorted(set(data.get("future_keywords") or []))

    schema = schema_header(
        "capabilities",
        "Structural model of OPA's capabilities.json: built-in catalog, Wasm ABI "
        "support matrix, future keywords, and feature flags.",
    )
    schema["imports"].append("./common")
    schema["source"] = _source_url("capabilities.json")
    schema["see_also"] = [
        "https://www.openpolicyagent.org/docs/policy-reference/",
    ]

    schema["classes"] = {
        "Capabilities": {
            "description": (
                "Top-level capabilities document published by an OPA build. "
                "Lists every built-in function the runtime supports along with "
                "Wasm ABI compatibility, future keywords and feature flags."
            ),
            "tree_root": True,
            "attributes": {
                "builtins": {
                    "description": "All built-in functions supported by this OPA build.",
                    "range": "Builtin",
                    "multivalued": True,
                    "inlined": True,
                    "inlined_as_list": True,
                },
                "future_keywords": {
                    "description": "Keywords reserved for future Rego releases.",
                    "range": "FutureKeyword",
                    "multivalued": True,
                },
                "wasm_abi_versions": {
                    "description": "Wasm ABI versions the runtime can host.",
                    "range": "WasmABIVersion",
                    "multivalued": True,
                    "inlined": True,
                    "inlined_as_list": True,
                },
                "features": {
                    "description": "Optional language / runtime features enabled in this build.",
                    "range": "FeatureName",
                    "multivalued": True,
                },
                "allow_net": {
                    "description": (
                        "Network destinations the built-ins are allowed to contact. "
                        "Absent or empty means unrestricted; an empty list means no network access."
                    ),
                    "range": "string",
                    "multivalued": True,
                },
            },
        },
        "Builtin": {
            "description": "A Rego built-in function exposed by the OPA runtime.",
            "attributes": {
                "name": {
                    "description": "Built-in identifier (dotted path, e.g. ``array.concat``).",
                    "identifier": True,
                    "range": "string",
                    "required": True,
                },
                "decl": {
                    "description": "Type declaration: signature plus return type.",
                    "range": "BuiltinDecl",
                    "required": True,
                    "inlined": True,
                },
                "infix": {
                    "description": "Optional infix operator symbol (e.g. ``&``, ``==``).",
                    "range": "string",
                },
                "deprecated": {
                    "description": "True when the built-in is scheduled for removal.",
                    "range": "boolean",
                },
                "nondeterministic": {
                    "description": "True when invocations may produce different results across runs.",
                    "range": "boolean",
                },
                "relation": {
                    "description": "True when the built-in is a relation (binds output variables).",
                    "range": "boolean",
                },
            },
        },
        "BuiltinDecl": {
            "description": "Type declaration of a built-in: function signature and return type.",
            "attributes": {
                "type": {
                    "description": "Always the literal string ``function``.",
                    "range": "string",
                    "required": True,
                    "equals_string": "function",
                },
                "args": {
                    "description": "Positional argument types in declaration order.",
                    "range": "TypeDecl",
                    "multivalued": True,
                    "inlined": True,
                    "inlined_as_list": True,
                },
                "result": {
                    "description": "Type of the result returned by the built-in.",
                    "range": "TypeDecl",
                    "inlined": True,
                },
                "variadic": {
                    "description": (
                        "When present, indicates the built-in accepts any number of trailing "
                        "arguments of this type."
                    ),
                    "range": "TypeDecl",
                    "inlined": True,
                },
            },
        },
        "TypeDecl": {
            "description": (
                "Recursive type expression used throughout Capabilities declarations.\n"
                "\n"
                "All slots are optional because TypeDecl doubles as the structural envelope\n"
                "for the various heterogeneous shapes the source JSON uses:\n"
                "* ``string|number|boolean|null|function`` -- atomic; only ``type`` is set.\n"
                "* ``any`` -- ``of`` is a list of alternative TypeDecls.\n"
                "* ``set`` -- ``of`` holds the (single) element TypeDecl.\n"
                "* ``array`` -- ``dynamic`` is the homogeneous element TypeDecl, or\n"
                "  ``static`` is an ordered list describing a fixed-length tuple.\n"
                "* ``object`` -- ``static`` lists named property pairs (TypeDecls with\n"
                "  ``key`` and ``value`` populated); ``dynamic`` is a TypeDecl whose\n"
                "  ``key``/``value`` describe additional property typing.\n"
                "* Inside an ``object``'s ``dynamic`` value, the TypeDecl has only\n"
                "  ``key`` and ``value`` populated -- ``type`` is absent.\n"
            ),
            "attributes": {
                "type": {
                    "description": "Discriminator: the kind of value this TypeDecl describes.",
                    "range": "BuiltinTypeKind",
                },
                "of": {
                    "description": (
                        "Element type(s). For ``set`` it is the (single) element type; for ``any`` "
                        "it is a union of alternative types. Always represented as a list -- the "
                        "instance generator wraps source scalar values for shape uniformity."
                    ),
                    "range": "TypeDecl",
                    "multivalued": True,
                    "inlined": True,
                    "inlined_as_list": True,
                },
                "dynamic": {
                    "description": (
                        "For ``array`` types this is the element TypeDecl; for ``object`` "
                        "types it is a TypeDecl with ``key`` and ``value`` populated."
                    ),
                    "range": "TypeDecl",
                    "inlined": True,
                },
                "static": {
                    "description": (
                        "Either named property pairs of an ``object`` TypeDecl (each entry has "
                        "``key`` and ``value`` populated) or positional tuple element TypeDecls "
                        "of a fixed-length ``array`` TypeDecl. Same recursive TypeDecl shape."
                    ),
                    "range": "TypeDecl",
                    "multivalued": True,
                    "inlined": True,
                    "inlined_as_list": True,
                },
                "key": {
                    "description": (
                        "Key of an object's dynamic-property mapping or static-property "
                        "entry. When the parent TypeDecl is an object's ``dynamic`` slot, "
                        "this is itself a TypeDecl (e.g. ``{type: string}``); when the "
                        "parent is an object's ``static`` entry, it is a string literal "
                        "naming the property."
                    ),
                    "range": "Any",
                    "inlined": True,
                },
                "value": {
                    "description": (
                        "Value type of an object's dynamic property mapping or static property "
                        "entry. Always a TypeDecl."
                    ),
                    "range": "TypeDecl",
                    "inlined": True,
                },
            },
        },
        "WasmABIVersion": {
            "description": "A supported Wasm ABI version pair.",
            "attributes": {
                "version": {
                    "description": "Major ABI version.",
                    "range": "integer",
                    "required": True,
                },
                "minor_version": {
                    "description": "Minor ABI version.",
                    "range": "integer",
                    "required": True,
                },
            },
        },
    }

    schema["enums"] = {
        "BuiltinTypeKind": {
            "description": "Kinds of value that a TypeDecl can describe.",
            "permissible_values": {k: {"description": k} for k in CAPABILITIES_TYPE_KINDS},
        },
        "FeatureName": {
            "description": (
                "Optional features advertised by the OPA build. The permissible values "
                "below are seeded from the upstream capabilities.json snapshot at "
                "generation time; future releases may introduce new flags."
            ),
            "permissible_values": {v: {"description": v, "meaning": f"openpolicyagent:feature/{v}"} for v in feature_values}
            or {"_placeholder": {"description": "No features in source"}},
        },
        "FutureKeyword": {
            "description": "Identifiers reserved for upcoming Rego releases.",
            "permissible_values": {v: {"description": v, "meaning": f"openpolicyagent:future_keyword/{v}"} for v in future_keyword_values}
            or {"_placeholder": {"description": "No future keywords in source"}},
        },
    }

    return schema


def _normalize_typedecl(node: Any) -> Any:
    """Normalize a TypeDecl-shaped node: ``of`` is always a list of TypeDecls.

    The source capabilities.json uses ``of`` as either a single TypeDecl (for
    ``set``) or a list of TypeDecls (for ``any``). LinkML multivalued slots
    require list-form, so we wrap scalar ``of`` values as one-element lists.
    Recurses into ``of``, ``dynamic``, ``static``, ``key``, ``value``.
    """
    if not isinstance(node, dict):
        return node
    out: dict[str, Any] = {}
    for k, v in node.items():
        if k == "of":
            if isinstance(v, list):
                out[k] = [_normalize_typedecl(item) for item in v]
            else:
                out[k] = [_normalize_typedecl(v)]
        elif k in ("dynamic", "key", "value"):
            out[k] = _normalize_typedecl(v)
        elif k == "static":
            out[k] = [_normalize_typedecl(item) for item in v]
        elif k == "args":
            out[k] = [_normalize_typedecl(item) for item in v]
        elif k == "result":
            out[k] = _normalize_typedecl(v)
        elif k == "variadic":
            out[k] = _normalize_typedecl(v)
        else:
            out[k] = v
    return out


def build_capabilities_instance(data: dict) -> dict:
    """Return capabilities.json reshaped as a Capabilities instance."""
    instance: dict[str, Any] = {}
    if data.get("builtins"):
        instance["builtins"] = [
            {**b, "decl": _normalize_typedecl(b["decl"])} if "decl" in b else b
            for b in data["builtins"]
        ]
    if data.get("future_keywords"):
        instance["future_keywords"] = list(data["future_keywords"])
    if data.get("wasm_abi_versions"):
        instance["wasm_abi_versions"] = data["wasm_abi_versions"]
    if data.get("features"):
        instance["features"] = list(data["features"])
    if data.get("allow_net") is not None:
        instance["allow_net"] = list(data["allow_net"])
    return instance


# --------------------------------------------------------------------------- #
# Module: builtin_metadata                                                    #
# --------------------------------------------------------------------------- #


def build_builtin_metadata_schema(data: dict) -> dict:
    """Build the LinkML schema describing builtin_metadata.json shape."""
    category_names = sorted((data.get("_categories") or {}).keys())

    schema = schema_header(
        "builtin_metadata",
        "Human-friendly catalog of Rego built-ins: documentation strings, argument "
        "names, version availability and category grouping. Source: ``builtin_metadata.json``.",
    )
    schema["source"] = _source_url("builtin_metadata.json")

    schema["classes"] = {
        "BuiltinMetadataCatalog": {
            "description": (
                "Wrapper class for the contents of ``builtin_metadata.json``. The source "
                "document is a flat map keyed by built-in name plus a ``_categories`` map; "
                "the generator script reshapes it so ``categories`` and ``builtins`` are "
                "explicit, inlined-as-dict slots on this wrapper."
            ),
            "tree_root": True,
            "attributes": {
                "categories": {
                    "description": "Category name -> list of built-in names belonging to it.",
                    "range": "BuiltinCategoryGroup",
                    "multivalued": True,
                    "inlined": True,
                    "inlined_as_list": False,
                },
                "builtins": {
                    "description": "All documented built-ins keyed by name.",
                    "range": "BuiltinMetadata",
                    "multivalued": True,
                    "inlined": True,
                    "inlined_as_list": False,
                },
            },
        },
        "BuiltinCategoryGroup": {
            "description": "Membership of built-ins in a documentation category.",
            "attributes": {
                "name": {
                    "description": (
                        "Category identifier. Plain string (not the BuiltinCategory "
                        "enum) so gen-python's identifier-slot machinery does not "
                        "forward-reference the enum class."
                    ),
                    "identifier": True,
                    "range": "string",
                    "required": True,
                },
                "category": {
                    "description": "Same value as ``name``, typed against the BuiltinCategory enum for downstream consumers.",
                    "range": "BuiltinCategory",
                },
                "builtins": {
                    "description": "Names of the built-ins belonging to this category.",
                    "range": "string",
                    "multivalued": True,
                    "required": True,
                },
            },
        },
        "BuiltinMetadata": {
            "description": "Human-readable metadata for a single Rego built-in function.",
            "attributes": {
                "name": {
                    "description": "Built-in identifier (dotted path).",
                    "identifier": True,
                    "range": "string",
                    "required": True,
                },
                "description": {
                    "description": "Markdown description of the built-in.",
                    "range": "string",
                },
                "introduced": {
                    "description": "Earliest OPA release tag in which the built-in was available.",
                    "range": "string",
                },
                "available": {
                    "description": "Every OPA release tag in which the built-in is available.",
                    "range": "string",
                    "multivalued": True,
                },
                "wasm": {
                    "description": "True if the built-in is implemented for the Wasm target.",
                    "range": "boolean",
                },
                "infix": {
                    "description": "Optional infix operator symbol.",
                    "range": "string",
                },
                "deprecated": {
                    "description": "True when the built-in is scheduled for removal.",
                    "range": "boolean",
                },
                "relation": {
                    "description": "True when the built-in is a relation.",
                    "range": "boolean",
                },
                "args": {
                    "description": "Positional argument descriptors in declaration order.",
                    "range": "BuiltinArg",
                    "multivalued": True,
                    "inlined": True,
                    "inlined_as_list": True,
                },
                "result": {
                    "description": "Descriptor for the value returned by the built-in.",
                    "range": "BuiltinResult",
                    "inlined": True,
                },
            },
        },
        "BuiltinArg": {
            "description": "Documentation for one positional argument of a built-in.",
            "attributes": {
                "name": {
                    "description": "Argument identifier as documented (often single-letter).",
                    "range": "string",
                },
                "description": {
                    "description": "Markdown description of the argument.",
                    "range": "string",
                },
                "type": {
                    "description": (
                        "Compact textual form of the argument type "
                        "(e.g. ``number``, ``set[any]``, ``any<string, number>``)."
                    ),
                    "range": "string",
                },
            },
        },
        "BuiltinResult": {
            "description": "Documentation for the value returned by a built-in.",
            "attributes": {
                "name": {
                    "description": "Result identifier as documented.",
                    "range": "string",
                },
                "description": {
                    "description": "Markdown description of the result.",
                    "range": "string",
                },
                "type": {
                    "description": "Compact textual form of the result type.",
                    "range": "string",
                },
            },
        },
    }

    schema["enums"] = {
        "BuiltinCategory": {
            "description": (
                "Documentation category a built-in belongs to. Permissible values are "
                "seeded from ``builtin_metadata.json._categories`` at generation time. "
                "Enum symbols follow LinkML's snake_case convention; each permissible "
                "value carries the upstream label (e.g. ``providers.aws``) in both its "
                "description and its ``meaning`` mapping."
            ),
            "permissible_values": {
                _slug(c): {"description": c, "meaning": f"openpolicyagent:category/{c}"}
                for c in category_names
            },
        },
    }

    return schema


def _slug(value: str) -> str:
    """Convert a free-form category label into a LinkML-safe enum symbol."""
    return value.replace(".", "_").replace("-", "_").replace(" ", "_")


def build_builtin_metadata_instance(data: dict) -> dict:
    """Reshape ``builtin_metadata.json`` into a BuiltinMetadataCatalog instance.

    The source mixes ``_categories`` with flat builtin entries at the top level;
    here we lift them under explicit ``categories`` and ``builtins`` keys keyed
    by name so the document matches the LinkML schema exactly.
    """
    cats = data.get("_categories") or {}
    categories = {
        _slug(name): {
            "name": _slug(name),
            "category": _slug(name),
            "builtins": list(members),
        }
        for name, members in sorted(cats.items())
    }

    builtins: dict[str, Any] = {}
    for name, entry in sorted(data.items()):
        if name.startswith("_"):
            continue
        if not isinstance(entry, dict):
            continue
        record: dict[str, Any] = {"name": name}
        for key in (
            "description",
            "introduced",
            "available",
            "wasm",
            "infix",
            "deprecated",
            "relation",
        ):
            if key in entry and entry[key] not in (None, ""):
                record[key] = entry[key]
        if entry.get("args"):
            record["args"] = list(entry["args"])
        if entry.get("result"):
            record["result"] = entry["result"]
        builtins[name] = record

    return {"categories": categories, "builtins": builtins}


# --------------------------------------------------------------------------- #
# Module: version_index                                                       #
# --------------------------------------------------------------------------- #


def build_version_index_schema(data: dict) -> dict:
    """Build the LinkML schema describing version_index.json."""
    schema = schema_header(
        "version_index",
        "OPA release in which each built-in, keyword, and feature was first introduced. "
        "Source: ``v1/ast/version_index.json``.",
    )
    schema["source"] = _source_url("v1/ast/version_index.json")

    schema["classes"] = {
        "VersionIndex": {
            "description": (
                "Mapping from language-element names to the OPA semantic version that "
                "first introduced them. Grouped into built-ins, future-keywords, and features."
            ),
            "tree_root": True,
            "attributes": {
                "builtins": {
                    "description": "Built-in name -> introduction version.",
                    "range": "ElementVersion",
                    "multivalued": True,
                    "inlined": True,
                    "inlined_as_list": False,
                },
                "features": {
                    "description": "Feature flag -> introduction version.",
                    "range": "ElementVersion",
                    "multivalued": True,
                    "inlined": True,
                    "inlined_as_list": False,
                },
                "keywords": {
                    "description": "Future keyword -> introduction version.",
                    "range": "ElementVersion",
                    "multivalued": True,
                    "inlined": True,
                    "inlined_as_list": False,
                },
            },
        },
        "ElementVersion": {
            "description": "Semantic version triple identifying when an element was introduced.",
            "attributes": {
                "name": {
                    "description": "Name of the language element (built-in, keyword, or feature).",
                    "identifier": True,
                    "range": "string",
                    "required": True,
                },
                "major": {
                    "description": "Major version number (source field ``Major``).",
                    "range": "integer",
                    "required": True,
                    "minimum_value": 0,
                },
                "minor": {
                    "description": "Minor version number (source field ``Minor``).",
                    "range": "integer",
                    "required": True,
                    "minimum_value": 0,
                },
                "patch": {
                    "description": "Patch version number (source field ``Patch``).",
                    "range": "integer",
                    "required": True,
                    "minimum_value": 0,
                },
            },
        },
    }

    return schema


def build_version_index_instance(data: dict) -> dict:
    """Reshape version_index.json into a VersionIndex instance.

    The source JSON uses Go-style ``Major``/``Minor``/``Patch`` field names;
    we lowercase them here to match the snake_case LinkML schema slots.
    """
    out: dict[str, Any] = {}
    for group in ("builtins", "features", "keywords"):
        entries = data.get(group) or {}
        if not entries:
            continue
        out[group] = {
            name: {
                "name": name,
                "major": ver["Major"],
                "minor": ver["Minor"],
                "patch": ver["Patch"],
            }
            for name, ver in sorted(entries.items())
        }
    return out


# --------------------------------------------------------------------------- #
# Module: authorization_input                                                 #
# --------------------------------------------------------------------------- #


# JSON Schema range -> LinkML range. ``object`` becomes the free-form ``Any``
# class so the rendered LinkML accepts arbitrary nested data.
_JSONSCHEMA_RANGE_MAP = {
    "string": "string",
    "boolean": "boolean",
    "integer": "integer",
    "number": "float",
    "object": "Any",
}


def build_authorization_input_schema(data: dict) -> dict:
    """Build the LinkML schema describing authorizationPolicy.json."""
    schema = schema_header(
        "authorization_input",
        "Input document accepted by OPA's bundled HTTP API Authorization policy. "
        "Source: ``v1/schemas/authorizationPolicy.json``.",
    )
    schema["imports"].append("./common")
    schema["source"] = _source_url("v1/schemas/authorizationPolicy.json")
    schema["see_also"] = [
        "https://www.openpolicyagent.org/docs/management-decision-logs/",
    ]

    required = set(data.get("required") or [])
    props = data.get("properties") or {}

    attributes: dict[str, dict] = {}
    for prop, spec in props.items():
        attr: dict[str, Any] = {
            "description": _auth_input_description(prop, spec),
        }
        if spec.get("type") == "array":
            item = spec.get("items") or {}
            attr["range"] = _JSONSCHEMA_RANGE_MAP.get(item.get("type"), "string")
            attr["multivalued"] = True
        else:
            attr["range"] = _JSONSCHEMA_RANGE_MAP.get(spec.get("type"), "string")
        if attr["range"] == "Any":
            # Inlined free-form objects need explicit inlining hints.
            attr["inlined"] = True
        if prop in required:
            attr["required"] = True
        attributes[prop] = attr

    schema["classes"] = {
        "AuthorizationInput": {
            "description": (
                "Input document the example HTTP API Authorization policy receives. "
                "Mirrors the OPA-provided JSON Schema at "
                "``v1/schemas/authorizationPolicy.json``."
            ),
            "tree_root": True,
            "attributes": attributes,
        },
    }

    return schema


def _auth_input_description(prop: str, _spec: dict) -> str:
    table = {
        "identity": "Caller identity, typically extracted from an authentication token.",
        "client_certificates": (
            "Client certificates presented during the TLS handshake. The example "
            "schema leaves the item shape opaque (free-form objects)."
        ),
        "method": "HTTP method of the request being authorized (e.g. ``GET``, ``POST``).",
        "path": (
            "Request URL path split on ``/`` and decoded into a list of path segments."
        ),
        "params": "Query-string parameters as a free-form object.",
        "headers": "Request headers as a free-form object (case insensitive in HTTP).",
        "body": "Decoded request body as a free-form object.",
    }
    return table.get(prop, f"Property `{prop}` from authorizationPolicy.json.")


def build_authorization_input_instance(_data: dict) -> dict:
    """Return a representative AuthorizationInput instance.

    The upstream JSON Schema does not ship sample data, so we synthesize a
    plausible example that exercises every required slot.
    """
    return {
        "identity": "alice",
        "client_certificates": [],
        "method": "GET",
        "path": ["v1", "data", "example", "allow"],
        "params": {},
        "headers": {"Accept": "application/json"},
        "body": {},
    }


# --------------------------------------------------------------------------- #
# Generic JSON-Schema (draft 2020-12) -> LinkML converter                     #
# --------------------------------------------------------------------------- #
#
# Used by the ``bundle_manifest`` and ``ir_plan`` generators below. Both
# upstream files ship as JSON Schema 2020-12 with ``$defs``-based modular
# class definitions, a top-level ``$ref`` naming the root class, and (for IR
# plan) ``oneOf`` discriminator wrappers for sum types.
#
# Limitations -- this is intentionally narrow rather than a fully-general
# JSON-Schema-to-LinkML converter:
#
# * Only ``type: object`` defs translate to LinkML classes; ``oneOf`` defs
#   become tagged-wrapper classes with a ``type`` slot and a payload of
#   range ``Any`` (see ``_convert_oneof_def``).
# * ``additionalProperties`` is informational only; LinkML does not enforce
#   closed-shape semantics at validation time for inline attributes.
# * Nullable types written as ``type: [array, null]`` are flattened to the
#   non-null variant (LinkML uses ``required: false`` rather than nullable).
# * Property names that collide with Python keywords are remapped via
#   ``_PYTHON_KEYWORD_REMAP``; the original wire-format key is preserved in
#   the slot description so consumers can round-trip to upstream JSON.


# Python keywords that appear as JSON Schema property names in OPA's upstream
# schemas and would otherwise produce invalid Python from ``gen-python``.
# The renamed slot still validates LinkML instances; downstream tooling that
# needs to round-trip with raw OPA output must apply this rename (e.g. via a
# JSON key-rename step).
_PYTHON_KEYWORD_REMAP = {
    "return": "return_value",
}


def _jsonschema_to_linkml_range(spec: dict) -> str:
    """Map a JSON-Schema property ``type`` to a LinkML range name."""
    t = spec.get("type")
    if isinstance(t, list):
        # Nullable wrappers: pick the first non-null member.
        t = next((v for v in t if v != "null"), None)
    return {
        "string": "string",
        "integer": "integer",
        "number": "float",
        "boolean": "boolean",
        "object": "Any",
    }.get(t, "string")


def _convert_property(spec: dict, prop: str, owner: str) -> dict:
    """Translate one JSON-Schema property to a LinkML attribute definition.

    Handles:
    * ``$ref`` -> range = referenced class name.
    * ``type: array`` with ``items: {$ref}`` -> multivalued range.
    * ``type: array`` with primitive items -> multivalued primitive range.
    * Scalar ``type`` -> primitive range.

    Always sets a ``description`` (synthesised from ``prop``/``owner`` when
    the source schema does not provide one) so ``linkml-lint`` does not warn
    about the auto-generated slots from ``$defs``.
    """
    attr: dict[str, Any] = {}
    if "description" in spec:
        attr["description"] = spec["description"]
    else:
        attr["description"] = f"``{prop}`` field of ``{owner}`` (from upstream JSON Schema)."
    if "$ref" in spec:
        attr["range"] = spec["$ref"].rsplit("/", 1)[-1]
        attr["inlined"] = True
        return attr
    t = spec.get("type")
    if isinstance(t, list):
        t = next((v for v in t if v != "null"), None)
    if t == "array":
        items = spec.get("items") or {}
        if "$ref" in items:
            attr["range"] = items["$ref"].rsplit("/", 1)[-1]
            attr["inlined"] = True
            attr["inlined_as_list"] = True
        else:
            attr["range"] = _jsonschema_to_linkml_range(items)
        attr["multivalued"] = True
        return attr
    if t == "object":
        # ``additionalProperties`` map -> open object, modelled as Any.
        attr["range"] = "Any"
        attr["inlined"] = True
        return attr
    attr["range"] = _jsonschema_to_linkml_range(spec)
    return attr


def _convert_object_def(name: str, defn: dict) -> dict:
    """Translate a JSON-Schema object def to a LinkML class definition."""
    required = set(defn.get("required") or [])
    attributes: dict[str, dict] = {}
    for prop, spec in (defn.get("properties") or {}).items():
        slot_name = _PYTHON_KEYWORD_REMAP.get(prop, prop)
        attr = _convert_property(spec, prop, name)
        if slot_name != prop:
            attr["description"] = (
                f"{attr['description']} "
                f"(Renamed from upstream wire-format key ``{prop}`` to avoid the "
                "Python reserved word.)"
            )
        if prop in required:
            attr["required"] = True
        attributes[slot_name] = attr
    cls: dict[str, Any] = {
        "description": defn.get("description") or f"``{name}`` definition from upstream JSON Schema.",
    }
    if attributes:
        cls["attributes"] = attributes
    return cls


def _convert_oneof_def(name: str, defn: dict) -> tuple[dict, list[str]]:
    """Translate a ``oneOf`` discriminator def to a tagged-wrapper class.

    The IR plan schema models sum types (``Stmt``, ``Val``) as a ``oneOf`` of
    objects of shape ``{type: const <Tag>, <payload>: $ref <Tag>}``. We
    surface this as a single LinkML class with:

    * ``type`` slot -- a string carrying the discriminator tag (the set of
      allowed values is captured as a sibling enum so consumers can validate
      them; returned alongside the class).
        * Payload slot (``stmt``/``value``/...) -- ``range: Any`` plus ``any_of``
            over all referenced payload classes, so generated JSON Schema can emit
            a concrete ``anyOf`` union while retaining an escape hatch when upstream
            variants evolve.
    """
    tag_to_payload: list[tuple[str, str, str]] = []  # (tag, payload_slot, payload_class)
    payload_ranges: set[str] = set()
    payload_slot_name: str | None = None
    for variant in defn.get("oneOf") or []:
        props = variant.get("properties") or {}
        tag = (props.get("type") or {}).get("const")
        if not tag:
            continue
        for slot, slot_spec in props.items():
            if slot == "type":
                continue
            if "$ref" in slot_spec:
                payload_class = slot_spec["$ref"].rsplit("/", 1)[-1]
                tag_to_payload.append((tag, slot, payload_class))
                payload_ranges.add(payload_class)
                payload_slot_name = payload_slot_name or slot
                break
            payload_range = _jsonschema_to_linkml_range(slot_spec)
            tag_to_payload.append((tag, slot, payload_range))
            payload_ranges.add(payload_range)
            payload_slot_name = payload_slot_name or slot
            break
    payload_slot_name = payload_slot_name or "value"
    tags = [t for t, _, _ in tag_to_payload]
    tag_mapping = "\n".join(
        f"* ``{tag}`` -- payload class ``{cls}``"
        for tag, _, cls in tag_to_payload
    )
    payload_any_of = [{"range": range_name} for range_name in sorted(payload_ranges)]

    cls = {
        "description": (
            f"Tagged-wrapper class for the ``{name}`` discriminated union from\n"
            "the upstream JSON Schema.\n\n"
            f"The ``type`` slot carries the discriminator tag and the\n"
            f"``{payload_slot_name}`` slot carries the typed payload. Because the\n"
            f"payload class varies by tag, ``{payload_slot_name}`` is typed as\n"
            "``Any`` with an ``any_of`` union over the known payload classes;\n"
            "consumers select the concrete class using the table below.\n\n"
            f"{tag_mapping}"
        ),
        "attributes": {
            "type": {
                "description": f"Discriminator tag identifying the {name} variant.",
                "range": f"{name}Tag",
                "required": True,
            },
            payload_slot_name: {
                "description": "Typed payload; concrete class is selected by ``type``.",
                "range": "Any",
                "inlined": True,
                "required": True,
            },
        },
    }
    if payload_any_of:
        cls["attributes"][payload_slot_name]["any_of"] = payload_any_of
    return cls, tags


def _convert_jsonschema_module(
    js: dict,
    local: str,
    description: str,
    source_rel: str,
    see_also: list[str] | None = None,
) -> dict:
    """Convert a JSON-Schema 2020-12 document with ``$defs`` to a LinkML module.

    Handles only the subset needed for OPA's ``manifest.schema.json`` and
    ``plan.schema.json``: ``$defs`` are walked once, ``oneOf`` defs become
    tagged-wrapper classes, plain object defs become classes with attributes.
    """
    schema = schema_header(local, description)
    schema["imports"].append("./common")
    schema["source"] = _source_url(source_rel)
    if see_also:
        schema["see_also"] = see_also

    defs = js.get("$defs") or {}
    classes: dict[str, dict] = {}
    enums: dict[str, dict] = {}

    # Identify the root class (top-level ``$ref``).
    root_ref = js.get("$ref", "")
    root_name = root_ref.rsplit("/", 1)[-1] if root_ref else None

    # Identify aliases (defs that are themselves just ``$ref`` to another def)
    # so we can collapse them to ``is_a`` relationships rather than empty
    # standalone classes.
    aliases: dict[str, str] = {}
    for name, defn in defs.items():
        if set(defn.keys()) == {"$ref"} and defn["$ref"].startswith("#/$defs/"):
            aliases[name] = defn["$ref"].rsplit("/", 1)[-1]

    for name, defn in defs.items():
        if name in aliases:
            continue
        if "oneOf" in defn:
            cls, tags = _convert_oneof_def(name, defn)
            classes[name] = cls
            enums[f"{name}Tag"] = {
                "description": f"Permissible discriminator tags for the ``{name}`` union.",
                "permissible_values": {tag: {"description": tag} for tag in tags},
            }
        elif defn.get("type") == "object":
            classes[name] = _convert_object_def(name, defn)
        else:
            # Skip primitive/unknown defs; they are typically not modelled as
            # classes in LinkML.
            continue

    # Convert alias defs into ``is_a`` subclasses for clarity.
    for alias, target in aliases.items():
        if target in classes:
            classes[alias] = {
                "description": f"Alias for ``{target}`` (single-``$ref`` def in upstream JSON Schema).",
                "is_a": target,
            }

    if root_name and root_name in classes:
        classes[root_name]["tree_root"] = True

    schema["classes"] = classes
    if enums:
        schema["enums"] = enums
    return schema


# --------------------------------------------------------------------------- #
# Module: bundle_manifest                                                     #
# --------------------------------------------------------------------------- #


def build_bundle_manifest_schema(data: dict) -> dict:
    """Build the LinkML schema describing ``v1/bundle/manifest.schema.json``."""
    schema = _convert_jsonschema_module(
        data,
        local="bundle_manifest",
        description=(
            "Structural model of the ``.manifest`` file that ``opa build`` emits "
            "inside every bundle artifact (revision, roots, Wasm resolver entries, "
            "rego version pins, free-form metadata). Source: "
            "``v1/bundle/manifest.schema.json``."
        ),
        source_rel="v1/bundle/manifest.schema.json",
        see_also=[
            "https://www.openpolicyagent.org/docs/management-bundles/",
        ],
    )
    # Constrain `rego_version` to the closed set {0, 1} per OPA's bundle Go
    # code (``v1/bundle/bundle.go``): 0 = Rego v0 (legacy), 1 = Rego v1
    # (default since OPA 1.0). The upstream JSON Schema leaves the value as a
    # plain integer; we tighten it here so consumers can rely on the bound.
    rego_version_slot = (
        schema.get("classes", {})
        .get("Manifest", {})
        .get("attributes", {})
        .get("rego_version")
    )
    if rego_version_slot is not None:
        rego_version_slot["minimum_value"] = 0
        rego_version_slot["maximum_value"] = 1
        rego_version_slot["description"] = (
            "Rego language version pinned for files in this bundle. "
            "``0`` = Rego v0 (legacy); ``1`` = Rego v1 (default since OPA 1.0). "
            "See ``v1/bundle/bundle.go`` for the canonical mapping."
        )

    # Tighten ``file_rego_versions`` from free-form object to a typed list of
    # file/version records. This increases validation strength while preserving
    # representational flexibility through inlined list form.
    manifest_attrs = schema.get("classes", {}).get("Manifest", {}).get("attributes", {})
    file_rego_versions_slot = manifest_attrs.get("file_rego_versions")
    if file_rego_versions_slot is not None:
        file_rego_versions_slot["description"] = (
            "Per-file Rego language version overrides. Each record maps a bundle "
            "file path to ``version`` where ``0`` = Rego v0 and ``1`` = Rego v1."
        )
        file_rego_versions_slot["range"] = "FileRegoVersion"
        file_rego_versions_slot["multivalued"] = True
        file_rego_versions_slot["inlined"] = True
        file_rego_versions_slot["inlined_as_list"] = True

    schema.setdefault("classes", {})["FileRegoVersion"] = {
        "description": (
            "Typed override record for ``Manifest.file_rego_versions``. "
            "Provides stronger validation than a free-form map while keeping "
            "the same semantics."
        ),
        "attributes": {
            "path": {
                "description": "Bundle-relative file path receiving a Rego version override.",
                "identifier": True,
                "required": True,
                "range": "string",
            },
            "version": {
                "description": "Rego version for this file: ``0`` (v0) or ``1`` (v1).",
                "required": True,
                "range": "integer",
                "minimum_value": 0,
                "maximum_value": 1,
            },
        },
    }

    return schema


def build_bundle_manifest_instance(_data: dict) -> dict:
    """Return a representative Manifest instance.

    Modelled after the real ``.manifest`` files under ``v1/sdk/testdata`` and
    extended with optional fields so every slot in the generated class is
    exercised at least once.
    """
    return {
        "revision": "2025-01-15T00:00:00Z",
        "roots": ["example/authz"],
        "rego_version": 1,
        "file_rego_versions": [
            {
                "path": "example/legacy.rego",
                "version": 0,
            }
        ],
        "metadata": {
            "owner": "team-platform",
        },
        "wasm": [
            {
                "entrypoint": "example/authz/allow",
                "module": "/policy.wasm",
            }
        ],
    }


# --------------------------------------------------------------------------- #
# Module: ir_plan                                                             #
# --------------------------------------------------------------------------- #


def build_ir_plan_schema(data: dict) -> dict:
    """Build the LinkML schema describing ``v1/ir/plan.schema.json``."""
    return _convert_jsonschema_module(
        data,
        local="ir_plan",
        description=(
            "Structural model of the Intermediate Representation (IR) plan that "
            "``opa build -t plan`` emits: top-level ``Policy`` containing "
            "``static`` constants, ``plans`` (entry points) and ``funcs`` (helper "
            "functions), each built from ``Block``s of typed ``Stmt`` records. "
            "Source: ``v1/ir/plan.schema.json``."
        ),
        source_rel="v1/ir/plan.schema.json",
        see_also=[
            "https://www.openpolicyagent.org/docs/ir/",
        ],
    )


def build_ir_plan_instance(_data: dict) -> dict:
    """Return a minimal Policy instance exercising the top-level shape.

    Encodes a trivial plan equivalent to ``package example; allow := true``:
    a single plan ``example/allow`` whose only block returns local ``0``
    after assigning the constant ``true``. The discriminator wrappers use
    the same tagged shape as the upstream JSON Schema. A stub helper
    function is included so the required ``Funcs.funcs`` / ``Func.params``
    multivalued slots have at least one entry (gen-python's runtime treats
    empty lists as missing values).
    """
    return {
        "static": {
            "strings": [{"value": "example/allow"}],
            "files": [{"value": "example.rego"}],
            "builtin_funcs": [],
        },
        "plans": {
            "plans": [
                {
                    "name": "example/allow",
                    "blocks": [
                        {
                            "stmts": [
                                {
                                    "type": "AssignVarStmt",
                                    "stmt": {
                                        "col": 1,
                                        "file": 0,
                                        "row": 1,
                                        "source": {"type": "bool", "value": True},
                                        "target": 1,
                                    },
                                },
                                {
                                    "type": "ResultSetAddStmt",
                                    "stmt": {
                                        "col": 1,
                                        "file": 0,
                                        "row": 1,
                                        "value": 1,
                                    },
                                },
                            ]
                        }
                    ],
                }
            ]
        },
        "funcs": {
            "funcs": [
                {
                    "name": "g0.example.allow",
                    "params": [1],
                    "return_value": 2,
                    "path": ["g0", "example", "allow"],
                    "blocks": [
                        {
                            "stmts": [
                                {
                                    "type": "ReturnLocalStmt",
                                    "stmt": {
                                        "col": 1,
                                        "file": 0,
                                        "row": 1,
                                        "source": 2,
                                    },
                                }
                            ]
                        }
                    ],
                }
            ]
        },
    }


# --------------------------------------------------------------------------- #
# Module: umbrella opa.yaml                                                   #
# --------------------------------------------------------------------------- #


UMBRELLA_MODULES = [
    "common",
    "capabilities",
    "builtin_metadata",
    "version_index",
    "authorization_input",
    "bundle_manifest",
    "ir_plan",
]


def build_umbrella_schema() -> dict:
    schema = {
        "id": "https://w3id.org/lmodel/opa",
        "name": "opa",
        "title": "Open Policy Agent (OPA)",
        "description": (
            "Umbrella LinkML schema for Open Policy Agent (OPA) and the Rego policy "
            "language. Imports per-source submodules generated from upstream OPA "
            "artifacts (capabilities, built-in metadata, version index, sample "
            "authorization input, bundle manifest, and IR plan)."
        ),
        "license": "Apache-2.0",
        "version": SCHEMA_VERSION,
        "see_also": [
            "https://www.openpolicyagent.org/",
            "https://lmodel.github.io/opa",
        ],
        "source": _OPA_SOURCE_BASE.rstrip("/"),
        "prefixes": {
            "openpolicyagent": "https://w3id.org/lmodel/opa/",
            "linkml": "https://w3id.org/linkml/",
            "schema": "http://schema.org/",
            "dcterms": "http://purl.org/dc/terms/",
            "rdfs": "http://www.w3.org/2000/01/rdf-schema#",
        },
        "default_prefix": "openpolicyagent",
        "default_range": "string",
        "imports": ["linkml:types"] + [f"./{m}" for m in UMBRELLA_MODULES],
        "subsets": {
            "opa_core_elements": {
                "description": "Primary document/root entities across OPA modules.",
            },
            "opa_supporting_elements": {
                "description": "Supporting structural or helper entities across modules.",
            },
        },
    }
    return schema


# --------------------------------------------------------------------------- #
# Per-source generator entry points                                            #
# --------------------------------------------------------------------------- #


def build_common_schema() -> dict:
    """Schema for shared cross-module definitions."""
    schema = schema_header(
        "common",
        (
            "Cross-cutting definitions shared by other OPA submodules (currently the "
            "``Any`` placeholder used for heterogeneous source values). Kept in a "
            "separate module so that re-imports from the umbrella schema do not "
            "produce duplicate-class merge conflicts."
        ),
    )
    schema["classes"] = {
        "Any": {
            "description": (
                "Free-form value placeholder (scalar, list, or object). Used to model "
                "source slots whose representation is heterogeneous or intentionally "
                "open (e.g. ``TypeDecl.key``, ``AuthorizationInput.body``)."
            ),
            "class_uri": "linkml:Any",
            "comments": [
                "Single shared definition mapped to ``linkml:Any`` (per metamodel) to avoid duplicate-class collisions across imported modules.",
                "Usage is concentrated at real polymorphism boundaries: free-form HTTP payloads, bundle metadata/annotations, discriminated-union payloads, and upstream-opaque JSON Schema slots.",
                "Usage is localized (roughly 11 sites across ~60 classes); most slots remain explicitly typed rather than defaulting to ``Any``.",
            ],
        },
    }
    return schema


def gen_common() -> None:
    dump_yaml(SCHEMA_DIR / "common.yaml", _finalize_schema(build_common_schema()))


def gen_capabilities() -> None:
    data = json.loads(CAPABILITIES_JSON.read_text())
    dump_yaml(
        SCHEMA_DIR / "capabilities.yaml",
        _finalize_schema(build_capabilities_schema(data)),
    )
    dump_yaml(TESTS_VALID / "Capabilities-current.yaml", build_capabilities_instance(data))


def gen_builtin_metadata() -> None:
    data = json.loads(BUILTIN_METADATA_JSON.read_text())
    dump_yaml(
        SCHEMA_DIR / "builtin_metadata.yaml",
        _finalize_schema(build_builtin_metadata_schema(data)),
    )
    dump_yaml(
        TESTS_VALID / "BuiltinMetadataCatalog-current.yaml",
        build_builtin_metadata_instance(data),
    )


def gen_version_index() -> None:
    data = json.loads(VERSION_INDEX_JSON.read_text())
    dump_yaml(
        SCHEMA_DIR / "version_index.yaml",
        _finalize_schema(build_version_index_schema(data)),
    )
    dump_yaml(
        TESTS_VALID / "VersionIndex-current.yaml",
        build_version_index_instance(data),
    )


def gen_authorization_input() -> None:
    data = json.loads(AUTH_INPUT_JSON.read_text())
    dump_yaml(
        SCHEMA_DIR / "authorization_input.yaml",
        _finalize_schema(build_authorization_input_schema(data)),
    )
    dump_yaml(
        TESTS_VALID / "AuthorizationInput-example.yaml",
        build_authorization_input_instance(data),
    )


def gen_bundle_manifest() -> None:
    data = json.loads(BUNDLE_MANIFEST_JSON.read_text())
    dump_yaml(
        SCHEMA_DIR / "bundle_manifest.yaml",
        _finalize_schema(build_bundle_manifest_schema(data)),
    )
    dump_yaml(
        TESTS_VALID / "Manifest-example.yaml",
        build_bundle_manifest_instance(data),
    )


def gen_ir_plan() -> None:
    data = json.loads(IR_PLAN_JSON.read_text())
    dump_yaml(
        SCHEMA_DIR / "ir_plan.yaml",
        _finalize_schema(build_ir_plan_schema(data)),
    )
    dump_yaml(
        TESTS_VALID / "Policy-example.yaml",
        build_ir_plan_instance(data),
    )


def gen_umbrella() -> None:
    dump_yaml(SCHEMA_DIR / "opa.yaml", build_umbrella_schema())


GENERATORS = {
    "umbrella": gen_umbrella,
    "common": gen_common,
    "capabilities": gen_capabilities,
    "builtins": gen_builtin_metadata,
    "version-index": gen_version_index,
    "auth-input": gen_authorization_input,
    "bundle-manifest": gen_bundle_manifest,
    "ir-plan": gen_ir_plan,
}


def gen_all() -> None:
    for name, fn in GENERATORS.items():
        print(f"-> {name}", file=sys.stderr)
        fn()


# --------------------------------------------------------------------------- #
# CLI                                                                          #
# --------------------------------------------------------------------------- #


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    targets = list(GENERATORS.keys()) + ["all"]
    parser.add_argument(
        "target",
        choices=targets,
        nargs="?",
        default="all",
        help="Which schema module to (re)generate. Defaults to ``all``.",
    )
    args = parser.parse_args(argv)
    if args.target == "all":
        gen_all()
    else:
        GENERATORS[args.target]()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
